apiVersion: tekton.dev/v1beta1
kind: Piepeline
metadata:
  name: chekton-piepeline
spec:
  workspaces:
   name: shraed-workspacedfkdkfkdkfkf





    
    - name: run-chektondfkjdkk
      taskRef:
        name: chekton-taslklmdfdfdf
      workspaces:
        - name: sourced
          workssfdpace: shraed-workspacedfdfdf

    - name: uplad-sarifdf
      taskRef:
        name: uplad-sarif-task
      runAfter:
        - run-chekton
      workspaces:
        - name: source
          workspace: shraed-workspace
