name: Checkton
on:
  pull_request:
    branches: [main]

jobs:
  checkton:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Checkton
        id: checkton
        uses: chmeliik/checkton@main
      - name: Upload SARIF File
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.checkton.outputs.sarif }}
          category: checkton
