name: Checkton
on:  # yamllint disable-line rule:truthy
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Differential Checkton requires full git history
          fetch-depth: 0

      - name: Run Checkton
        id: checkton
        uses: chmeliik/checkton@main
        with:
          # Let there be green. GitHub's code scanning will do the reporting.
          fail-on-findings: false
          find-copies-harder: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.checkton.outputs.sarif }}
          # Avoid clashing with ShellCheck
          category: checkton